version: '3.5'

services:
  db_crm:
    container_name: crm_system_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine